name: Build Unity Project and Create Pull Request

on:
  push:
    branches:
      - Develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Cache Unity packages
        uses: actions/cache@v3
        with:
          path: Library/PackageCache
          key: ${{ runner.os }}-unity-packages-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-unity-packages-

      - name: Clean previous build artifacts
        run: |
          if [ -d "build/WebGL" ]; then
            rm -rf build/WebGL
          fi

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          targetPlatform: WebGL

      - name: Upload WebGL Build
        uses: actions/upload-artifact@v3
        with:
          name: WebGLBuild
          path: build/WebGL

      - name: Checkout Develop branch
        uses: actions/checkout@v3
        with:
          ref: Develop

      - name: Download WebGL Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: WebGLBuild

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create Build Branch
        run: |
          BRANCH_NAME="Build-$(date +%s)"
          git checkout -b $BRANCH_NAME
          mkdir -p build/WebGL
          mv WebGLBuild/* build/WebGL/
          git add build/WebGL
          git commit -m "Add WebGL build artifacts"
          git push origin $BRANCH_NAME
          echo "::set-output name=branch_name::$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: DevBuild
          head: ${{ steps.create_build_branch.outputs.branch_name }}
          title: "Update DevBuild with latest WebGL build artifacts"
          body: "This PR includes the latest WebGL build artifacts."
          draft: false

      - name: Merge Pull Request
        uses: github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: context.actor + ":" + process.env.BRANCH_NAME,
              base: "DevBuild",
              state: "open"
            });
            if (pr.data.length > 0) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.data[0].number,
                merge_method: "merge"
              });
            }

      - name: Delete Build Branch
        if: success()
        run: |
          git push origin --delete $BRANCH_NAME
